hydra :
  job :
    name : filters-visualization-lite
  run :
    dir : exps/${hydra.job.name}

# The directory where the results are stored
output_directory: results

# List of directories where each model is stored
# PS: give the absolute path
# PS: make sure you use .keras files if you are tf >= 2.15
model_paths: ["/home/username/phd/msd-irimas/filter1D_visualization/lite_0_coffee.keras",
              "/home/username/phd/msd-irimas/filter1D_visualization/lite_1_coffee.keras"]

# List of layer indices to use for each of the models above
layer_indices: [-5, -5]

list_labels: ["lite_1_last_conv","lite_2_last_conv"]
list_colors: ["#FF5733", "#33FF57"]

# Similarity measure used for the filters
distance: "dtw"

# Figure title
title: "Filter 2D Visualization on Coffee Dataset"