output_directory: results
model_paths:
- /home/afawaz/phd/msd-irimas/filter1D_visualization/lite_0_coffee.keras
- /home/afawaz/phd/msd-irimas/filter1D_visualization/lite_1_coffee.keras
layer_indices:
- -5
- -5
list_labels:
- lite_1_last_conv
- lite_2_last_conv
list_colors:
- '#FF5733'
- '#33FF57'
distance: dtw
title: Filter 2D Visualization on Coffee Dataset
